#include "bitband.h"

#define FIO0DIR_ADDR 0x2009C000
#define FIO1DIR_ADDR 0x2009C020
#define FIO2DIR_ADDR 0x2009C040

#define FIO0PIN_ADDR 0x2009C014
#define FIO1PIN_ADDR 0x2009C034
#define FIO2PIN_ADDR 0x2009C054

#define FIO0SET_ADDR 0x2009C018
#define FIO1SET_ADDR 0x2009C038
#define FIO2SET_ADDR 0x2009C058

#define FIO0CLR_ADDR 0x2009C01C
#define FIO1CLR_ADDR 0x2009C03C
#define FIO2CLR_ADDR 0x2009C05C

#define FIO0SET_ALIAS(BIT_PAR) BIT_BAND2(FIO0SET_ADDR, BIT_PAR)
#define FIO1SET_ALIAS(BIT_PAR) BIT_BAND2(FIO1SET_ADDR, BIT_PAR)
#define FIO2SET_ALIAS(BIT_PAR) BIT_BAND2(FIO2SET_ADDR, BIT_PAR)

#define FIO0CLR_ALIAS(BIT_PAR) BIT_BAND2(FIO0CLR_ADDR, BIT_PAR)
#define FIO1CLR_ALIAS(BIT_PAR) BIT_BAND2(FIO1CLR_ADDR, BIT_PAR)
#define FIO2CLR_ALIAS(BIT_PAR) BIT_BAND2(FIO2CLR_ADDR, BIT_PAR)

#define FIO0PIN_ALIAS(BIT_PAR) BIT_BAND2(FIO0PIN_ADDR, BIT_PAR)
#define FIO1PIN_ALIAS(BIT_PAR) BIT_BAND2(FIO1PIN_ADDR, BIT_PAR)
#define FIO2PIN_ALIAS(BIT_PAR) BIT_BAND2(FIO2PIN_ADDR, BIT_PAR)

#define FIO0DIR_ALIAS(BIT_PAR) BIT_BAND2(FIO0DIR_ADDR, BIT_PAR)
#define FIO1DIR_ALIAS(BIT_PAR) BIT_BAND2(FIO1DIR_ADDR, BIT_PAR)
#define FIO2DIR_ALIAS(BIT_PAR) BIT_BAND2(FIO2DIR_ADDR, BIT_PAR)

#define FIO0DIR_ALIAS_PTR(BIT_PAR) BIT_BAND2_PTR(FIO0DIR_ADDR, BIT_PAR)
#define FIO1DIR_ALIAS_PTR(BIT_PAR) BIT_BAND2_PTR(FIO1DIR_ADDR, BIT_PAR)
#define FIO2DIR_ALIAS_PTR(BIT_PAR) BIT_BAND2_PTR(FIO2DIR_ADDR, BIT_PAR)

#define FIO0PIN_ALIAS_PTR(BIT_PAR) BIT_BAND2_PTR(FIO0PIN_ADDR, BIT_PAR)
#define FIO1PIN_ALIAS_PTR(BIT_PAR) BIT_BAND2_PTR(FIO1PIN_ADDR, BIT_PAR)
#define FIO2PIN_ALIAS_PTR(BIT_PAR) BIT_BAND2_PTR(FIO2PIN_ADDR, BIT_PAR)

#define FIO0SET_ALIAS_PTR(BIT_PAR) BIT_BAND2_PTR(FIO0SET_ADDR, BIT_PAR)
#define FIO1SET_ALIAS_PTR(BIT_PAR) BIT_BAND2_PTR(FIO1SET_ADDR, BIT_PAR)
#define FIO2SET_ALIAS_PTR(BIT_PAR) BIT_BAND2_PTR(FIO2SET_ADDR, BIT_PAR)

#define FIO0CLR_ALIAS_PTR(BIT_PAR) BIT_BAND2_PTR(FIO0CLR_ADDR, BIT_PAR)
#define FIO1CLR_ALIAS_PTR(BIT_PAR) BIT_BAND2_PTR(FIO1CLR_ADDR, BIT_PAR)
#define FIO2CLR_ALIAS_PTR(BIT_PAR) BIT_BAND2_PTR(FIO2CLR_ADDR, BIT_PAR)

extern void (*GpioHook)(void);
extern void GpioInit(void);
extern void GpioInterruptsEnable();
extern void GpioInterruptsDisable();